### ISSUE TITLE
RuntimeError: attempted adding second root element to document

### ISSUE THREAD

**Issue by bjeanes** [bugcrowd/test-summary-buildkite-plugin#42]
I'm just trying to wire this plugin up for the first time so may be doing something wrong, but...

My ESLint annotations come through, but my RSpec ones fail with the following output:

```
$ buildkite-agent artifact download tmp/rspec*.xml tmp/test-summary
  | 2018-12-14 05:48:27 INFO   Searching for artifacts: "tmp/rspec*.xml"
  | 2018-12-14 05:48:27 INFO   Found 4 artifacts. Starting to download to: /usr/src/app/tmp/test-summary
  | 2018-12-14 05:48:27 INFO   Successfully downloaded "tmp/rspec-6851529f-2c42-4030-8d93-19eb32e0db87.xml" 158119 bytes
  | 2018-12-14 05:48:27 INFO   Successfully downloaded "tmp/rspec-fed778c5-42ec-41bb-b6f3-1d427f6f677d.xml" 394107 bytes
  | 2018-12-14 05:48:27 INFO   Successfully downloaded "tmp/rspec-81677cf4-bff2-4353-97e6-e40310958b93.xml" 447761 bytes
  | 2018-12-14 05:48:27 INFO   Successfully downloaded "tmp/rspec-6492fbdd-064e-498d-9178-de6f8a8c0e13.xml" 460360 bytes
  |  
  | REXML::ParseException: #<RuntimeError: attempted adding second root element to document>
  | /usr/local/lib/ruby/2.5.0/rexml/document.rb:96:in `add'
  | /usr/local/lib/ruby/2.5.0/rexml/element.rb:904:in `add'
  | /usr/local/lib/ruby/2.5.0/rexml/child.rb:22:in `initialize'
  | /usr/local/lib/ruby/2.5.0/rexml/parent.rb:14:in `initialize'
  | /usr/local/lib/ruby/2.5.0/rexml/element.rb:60:in `initialize'
  | /usr/local/lib/ruby/2.5.0/rexml/element.rb:902:in `new'
  | /usr/local/lib/ruby/2.5.0/rexml/element.rb:902:in `add'
  | /usr/local/lib/ruby/2.5.0/rexml/element.rb:298:in `add_element'
  | /usr/local/lib/ruby/2.5.0/rexml/document.rb:103:in `add_element'
  | /usr/local/lib/ruby/2.5.0/rexml/parsers/treeparser.rb:34:in `parse'
  | /usr/local/lib/ruby/2.5.0/rexml/document.rb:288:in `build'
  | /usr/local/lib/ruby/2.5.0/rexml/document.rb:45:in `initialize'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:102:in `new'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:102:in `file_contents_to_failures'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:65:in `filename_to_failures'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:29:in `block in failures'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:29:in `map'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:29:in `failures'
  | /usr/src/app/lib/test_summary_buildkite_plugin/formatter.rb:22:in `markdown'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:49:in `input_markdown'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:60:in `block in markdown_with_truncation'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:60:in `map'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:60:in `markdown_with_truncation'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:17:in `markdown'
  | /usr/src/app/lib/test_summary_buildkite_plugin/runner.rb:19:in `run'
  | /usr/src/app/lib/test_summary_buildkite_plugin.rb:20:in `run'
  | ./bin/run:10:in `<main>'
  | ...
  | attempted adding second root element to document
  | Line: 69
  | Position: 14204
  | Last 80 unconsumed characters:
  |  
  |  
  | /usr/local/lib/ruby/2.5.0/rexml/parsers/treeparser.rb:96:in `rescue in parse'
  | /usr/local/lib/ruby/2.5.0/rexml/parsers/treeparser.rb:21:in `parse'
  | /usr/local/lib/ruby/2.5.0/rexml/document.rb:288:in `build'
  | /usr/local/lib/ruby/2.5.0/rexml/document.rb:45:in `initialize'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:102:in `new'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:102:in `file_contents_to_failures'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:65:in `filename_to_failures'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:29:in `block in failures'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:29:in `map'
  | /usr/src/app/lib/test_summary_buildkite_plugin/input.rb:29:in `failures'
  | /usr/src/app/lib/test_summary_buildkite_plugin/formatter.rb:22:in `markdown'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:49:in `input_markdown'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:60:in `block in markdown_with_truncation'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:60:in `map'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:60:in `markdown_with_truncation'
  | /usr/src/app/lib/test_summary_buildkite_plugin/truncater.rb:17:in `markdown'
  | /usr/src/app/lib/test_summary_buildkite_plugin/runner.rb:19:in `run'
  | /usr/src/app/lib/test_summary_buildkite_plugin.rb:20:in `run'
  | ./bin/run:10:in `<main>'
```

Only thing of note really here is that I am parallelising with Knapsack so there are multiple RSpec files to stitch together here...

Any ideas?

**Comment by tessereth** [comment]
Interesting, that's a new one for me. This plugin should be able to handle parallel specs fine. I would guess that error means at least one of those xml files has more than one root element. Can you download them and check? Junit files should contain a single `testsuites` or `testsuite` element at the root of the document.

**Comment by bjeanes** [comment]
I'll take a look!
