### ISSUE TITLE
handle junit error fields

### ISSUE THREAD

**Issue by micheletest** [bugcrowd/test-summary-buildkite-plugin#5]
I have some tests that output test failures into an xunit report with error fields rather than failure fields. These are for ember tests running with testem configured with xunit output. Would it be possible to also handle error fields?

Example XML

```xml
<testcase classname="Chrome 66.0" name="Unit | Component | autocomplete: shows default results when defaultCategory is set" time="0.070">
<error message="has results after focusing">
<![CDATA[
at Object.<anonymous> (http://localhost:9001/assets/tests.js:2188:20) at runTest (http://localhost:9001/assets/test-support.js:15012:30) at Test.run (http://localhost:9001/assets/test-support.js:14998:6) at http://localhost:9001/assets/test-support.js:15210:12 at advanceTaskQueue (http://localhost:9001/assets/test-support.js:14611:6) at Object.advance (http://localhost:9001/assets/test-support.js:14592:4)
]]>
</error>
</testcase>
```

**Comment by tessereth** [comment]
Can you test that #7 works for you? I can only test it with that single example so I'd like to be sure. Also if you have any suggestions for formatting I'm all ears. I'm just making stuff up as I go with whatever seems vaguely sane.

**Comment by micheletest** [comment]
@tessereth this worked great. The formatting seemed fine to me, I tried to generate errors on several different tests and the Message and Details all were correct and helpful. Thanks for the quick response.
