### ISSUE TITLE
Errors are ignored in junit.xml

### ISSUE THREAD

**Issue by vgrigoruk** [bugcrowd/test-summary-buildkite-plugin#62]
It looks like plugin ignores errors in `junit.xml`

Pipeline step:

```yml
  - label: test-summary
    plugins:
      - bugcrowd/test-summary#v1.11.0:
          inputs:
            - label: angular-tests
              artifact_path: .tmp/angular-junit.xml
              type: junit
            - label: browser-tests
              artifact_path: .tmp/test/junit/*.xml
              type: junit
          formatter:
            type: summary
```

junit xml that contains errors:

```xml
<testsuites>
  <testsuite name="parent_suite" timestamp="2020-04-07T22:57:13" time="1.956" tests="1" failures="0" errors="1" skipped="0">
    <properties>
      <property name="specId" value="0" />
      <property name="suiteName" value="parent_suite" />
      <property name="capabilities" value="chrome.80_0_3987_132.linux" />
      <property name="file" value="./test/features/group/browser-test.spec.js" />
    </properties>
    <testcase classname="chrome.80_0_3987_132.linux.parent_suite" name="test_case" time="0.446">
      <error message="done() called multiple times" />
      <system-err><![CDATA[Error: done() called multiple times at multiple (/app/node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runnable.js:314:26) at done (/app/node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runnable.js:326:14) at /app/node_modules/@wdio/mocha-framework/node_modules/mocha/lib/runnable.js:400:11 at processTicksAndRejections (internal/process/task_queues.js:97:5)]]></system-err>
    </testcase>
  </testsuite>
</testsuites>

```

plugin execution logs:

```
~~~ Running plugin test-summary command hook
$ /var/lib/buildkite-agent/plugins/github-com-bugcrowd-test-summary-buildkite-plugin-v1-11-0/hooks/command
Found tag v1.11.0, pulling from docker hub
v1.11.0: Pulling from bugcrowd/test-summary-buildkite-plugin
Digest: sha256:8341161915a5a5b44b814b4ac5ef257b46bc6784df6847718ac9761e45471c3b
Status: Image is up to date for bugcrowd/test-summary-buildkite-plugin:v1.11.0
docker.io/bugcrowd/test-summary-buildkite-plugin:v1.11.0
$ buildkite-agent artifact download .tmp/angular-junit.xml tmp/test-summary
2020-04-07 22:59:29 INFO   Searching for artifacts: ".tmp/angular-junit.xml"
2020-04-07 22:59:29 INFO   Found 1 artifacts. Starting to download to: /usr/src/app/tmp/test-summary
2020-04-07 22:59:30 INFO   Successfully downloaded ".tmp/angular-junit.xml" 98189 bytes

$ buildkite-agent artifact download .tmp/test/junit/*.xml tmp/test-summary
2020-04-07 22:59:30 INFO   Searching for artifacts: ".tmp/test/junit/*.xml"
2020-04-07 22:59:30 INFO   Found 29 artifacts. Starting to download to: /usr/src/app/tmp/test-summary
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-1.chrome.xml" 7137 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-3.chrome.xml" 2838 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-2.chrome.xml" 5752 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-0.chrome.xml" 13980 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-4.chrome.xml" 4580 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-5.chrome.xml" 1268 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-1.chrome.xml" 3414 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-0.chrome.xml" 18582 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-2.chrome.xml" 9335 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-3.chrome.xml" 1719 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-4.chrome.xml" 11362 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-0.chrome.xml" 8362 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-1.chrome.xml" 6402 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-2.chrome.xml" 11734 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-3.chrome.xml" 4031 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-5.chrome.xml" 963 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-4.chrome.xml" 8788 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-0.chrome.xml" 9772 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-1.chrome.xml" 6246 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-3.chrome.xml" 3165 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-4.chrome.xml" 2254 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-2.chrome.xml" 7680 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-5.chrome.xml" 919 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-1.chrome.xml" 7023 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-2.chrome.xml" 5306 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-3.chrome.xml" 2292 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-0.chrome.xml" 31582 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-4.chrome.xml" 5820 bytes
2020-04-07 22:59:31 INFO   Successfully downloaded ".tmp/test/junit/results-0-5.chrome.xml" 962 bytes

No errors found! 🎉
$ cd /var/lib/buildkite-agent/plugins/github-com-bugcrowd-test-summary-buildkite-plugin-v1-11-0
# OLDPWD changed
# PWD changed
```

**Comment by maschwenk** [comment]
We currently only support parsing of junit errors that look something along the lines of the artifacts in the repository:

https://github.com/bugcrowd/test-summary-buildkite-plugin/blob/master/spec/sample_artifacts/rspec-01234567-0011-0011-0011-001122334455.xml

Can you give a little more background about what is generating that Junit? Junit spec adherence seems to be quite inconsistent so we don't currently support all the various flavors in the community.

**Comment by vgrigoruk** [comment]
sorry, my fault. I didn't notice that files didn't contain JOB_ID in filename and the results were simply overwritten.
